name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22", "1.23", "1.24"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, 386]
        exclude:
          - os: macos-latest
            arch: 386 # macOS runners may not support GOARCH=386
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          architecture: ${{ matrix.arch }}
      - run: go test -v ./...
      - run: go test -bench=. ./...